### ISSUE TITLE
TypeError: Cannot read property 'importedIds' of null at findCSS

### ISSUE THREAD

**Issue by danielzzz** [PepsRyuu/rollup-plugin-hot-css#14]
hi I'm getting this error when trying to build the project. I am clueless..
thanks, dan

```
$ yarn clean && rollup -c --environment NODE_ENV:production
warning package.json: No license field
$ shx rm -rf dist

./src/index.js → dist...
[!] (plugin at position 1) TypeError: Cannot read property 'importedIds' of null
TypeError: Cannot read property 'importedIds' of null
    at findCSS (/media/daniel/lindata/proyectos/_moje/js/chat-client-rollup/node_modules/rollup-plugin-hot-css/index.js:171:39)
    at Object.renderChunk (/media/daniel/lindata/proyectos/_moje/js/chat-client-rollup/node_modules/rollup-plugin-hot-css/index.js:180:13)
    at /media/daniel/lindata/proyectos/_moje/js/chat-client-rollup/node_modules/rollup/dist/shared/rollup.js:20218:25

error Command failed with exit code 1.

```

this is my rollup.config.js

```
import node_resolve from '@rollup/plugin-node-resolve';
import babel from '@rollup/plugin-babel';
import hotcss from 'rollup-plugin-hot-css';
import commonjs from 'rollup-plugin-commonjs-alternate';
//import replace from '@rollup/plugin-replace';
import static_files from 'rollup-plugin-static-files';
import {terser} from 'rollup-plugin-terser';
import refresh from 'rollup-plugin-react-refresh';

let config = {
  input: './src/index.js',
  output: {
    dir: 'dist',
    format: 'esm',
    entryFileNames: '[name].[hash].js',
    assetFileNames: '[name].[hash][extname]',
  },
  plugins: [
    hotcss({
      hot: process.env.NODE_ENV === 'development',
      extensions: ['.css', '.scss'],
      file: 'styles.css',
    }),
    babel({
      exclude: 'node_modules/**',
      babelHelpers: 'bundled',
      presets: ['@babel/preset-env', '@babel/preset-react'],
    }),
    node_resolve({
      browser: true,
    }),
    commonjs({
      define: {
        'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
      },
    }),
    process.env.NODE_ENV === 'development' && refresh(),
  ],
};

if (process.env.NODE_ENV === 'production') {
  config.plugins = config.plugins.concat([
    static_files({
      include: ['./public'],
    }),
    terser(),
  ]);
}

export default config;

```

**Comment by PepsRyuu** [comment]
Are you on the latest version of the package?

**Comment by danielzzz** [comment]
I was not, sorry, I got it from create-nollup-up. 
after upgrading the package it worked fine. 

thanks!
dan
